config/routes.rb
Rails.application.routes.draw do
  resources :weather_logs
  root 'weather_logs#index', defaults: { format: :json }

end

app/models/weather_log.rb
class WeatherLog < ActiveRecord::Base

  # default_scope  do
  #   exclude_columns = %w(created_at updated_at dew_point_temperature visibility_distance precipitation_hour sea_level_pressure precipitation_depth_in_mm)
  #   filtered_cols = (column_names - exclude_columns.map(&:to_s)).map{|i| "weather_logs."+i}
  #   self.select(filtered_cols)
  # end

  GEOG_FACTORY ||= RGeo::Geographic.spherical_factory(:srid => 4326)
  set_rgeo_factory_for_column(:lonlat, GEOG_FACTORY)
  # RGeo::ActiveRecord::GeometryMixin.set_json_generator(:geojson)
  scope :nearby, lambda { |radius_in_km, lon, lat|
    point = GEOG_FACTORY.point(lon, lat)
    radius = radius_in_km.to_f*1000
    where("ST_DWithin(lonlat, ST_GeomFromText('#{point}'), #{radius} ) ")
    # .order("ST_Distance(lonlat, ST_Geomfromtext('#{point}'), #{radius}) ")
  }
end

app/controllers/weather_logs_controller.rb
class WeatherLogsController < ApplicationController
  before_action :set_weather_log, only: [:show, :edit, :update, :destroy]
  include GeoProcess
  # GET /weather_logs
  # GET /weather_logs.json
  def index
    begin
      start_time, end_time = get_start_time_and_end_time(params)
      longitude, latitude = get_longitude_and_latitude(params)
      fields = get_fields(params)
      if longitude and latitude
        q = WeatherLog.nearby(100, longitude, latitude)
      else
        q = WeatherLog.all
      end
      if start_time and end_time
        q = q.where(datetime: start_time..end_time)
      elsif start_time
        q =  q.where("datetime >= ?", start_time)
      elsif end_time
        q =  q.where("datetime <= ?", end_time)
      end

      @weather_logs = q.order(datetime: :asc).limit(2000)

      respond_to do |format|
        if fields
          format.json { render json: @weather_logs.as_json(only: fields)}
        else
          format.json { render json: @weather_logs.as_json(only: get_all_valid_fields)}
        end
      end
    rescue Exception => e
      respond_to do |format|
        format.json { render json: {status: "Invalid Request #{e}"} }
      end
    end
  end

  # GET /weather_logs/1
  # GET /weather_logs/1.json
  def show
  end

  # GET /weather_logs/new
  def new
    @weather_log = WeatherLog.new
  end

  # GET /weather_logs/1/edit
  def edit
  end

  # POST /weather_logs
  # POST /weather_logs.json
  def create
    @weather_log = WeatherLog.new(weather_log_params)

    respond_to do |format|
      if @weather_log.save
        format.html { redirect_to @weather_log, notice: 'Weather log was successfully created.' }
        format.json { render :show, status: :created, location: @weather_log }
      else
        format.html { render :new }
        format.json { render json: @weather_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_logs/1
  # PATCH/PUT /weather_logs/1.json
  def update
    respond_to do |format|
      if @weather_log.update(weather_log_params)
        format.html { redirect_to @weather_log, notice: 'Weather log was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_log }
      else
        format.html { render :edit }
        format.json { render json: @weather_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_logs/1
  # DELETE /weather_logs/1.json
  def destroy
    @weather_log.destroy
    respond_to do |format|
      format.html { redirect_to weather_logs_url, notice: 'Weather log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_log
      @weather_log = WeatherLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_log_params
      params.require(:weather_log).permit(:latitude, :longitude, :datatime, :air_temperature)
    end
end

app/helpers/weather_logs_helper.rb
module WeatherLogsHelper
end

app/views/weather_logs/_form.html.erb
<%= form_for(@weather_log) do |f| %>
  <% if @weather_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather_log.errors.count, "error") %> prohibited this weather_log from being saved:</h2>

      <ul>
      <% @weather_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :datatime %><br>
    <%= f.text_field :datatime %>
  </div>
  <div class="field">
    <%= f.label :air_temperature %><br>
    <%= f.text_field :air_temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_logs/edit.html.erb
<h1>Editing weather_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_log %> |
<%= link_to 'Back', weather_logs_path %>

app/views/weather_logs/index.html.erb
<% if @weather_logs %>
<h1>Listing weather_logs</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Datatime</th>
      <th>Air temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @weather_logs.each do |weather_log| %>
      <tr>
        <td><%= weather_log.latitude %></td>
        <td><%= weather_log.longitude %></td>
        <td><%= weather_log.datetime %></td>
        <td><%= weather_log.air_temperature %></td>
        <td><%= link_to 'Show', weather_log %></td>
        <td><%= link_to 'Edit', edit_weather_log_path(weather_log) %></td>
        <td><%= link_to 'Destroy', weather_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather log', new_weather_log_path %>
<% else %>
  <h1> Invalid Request </h1>
<% end %>

app/views/weather_logs/new.html.erb
<h1>New weather_log</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_logs_path %>

app/views/weather_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @weather_log.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @weather_log.longitude %>
</p>

<p>
  <strong>Datatime:</strong>
  <%= @weather_log.datatime %>
</p>

<p>
  <strong>Air temperature:</strong>
  <%= @weather_log.air_temperature %>
</p>

<%= link_to 'Edit', edit_weather_log_path(@weather_log) %> |
<%= link_to 'Back', weather_logs_path %>